// AUTO-GENERATED by scripts/generate-changelog-data.mjs from docs/edit logs/ — do not hand-edit.
// Regenerate with `npm run generate:changelog` (also runs automatically before dev/build/test/typecheck).

import type { ChangelogEntry } from "./changelogTypes";

export const LATEST_UPDATES: ChangelogEntry[] = [
  {
    "version": "v150.31",
    "date": "2026-09-29",
    "bucket": "fix",
    "scope": "distribution",
    "title": "delete guard fails safe on an unreadable event store; auto-lock decides from fresh state; per-workspace month-lock cache"
  },
  {
    "version": "v150.30",
    "date": "2026-09-29",
    "bucket": "fix",
    "scope": "distribution",
    "title": "review fixes for the reassign click-path work (delete guard, auto-lock ordering, deterministic index, persist retry)"
  },
  {
    "version": "v150.29",
    "date": "2026-09-29",
    "bucket": "fix",
    "scope": "distribution",
    "title": "remember that the legacy distribution log is absent"
  },
  {
    "version": "v150.28",
    "date": "2026-09-29",
    "bucket": "fix",
    "scope": "distribution",
    "title": "thread one DistributionLogLoad through the interactive append and drop a redundant listing"
  },
  {
    "version": "v150.27",
    "date": "2026-09-29",
    "bucket": "fix",
    "scope": "distribution",
    "title": "keep the log projection off an interactive single-row click"
  },
  {
    "version": "v150.26",
    "date": "2026-09-29",
    "bucket": "fix",
    "scope": "distribution",
    "title": "rewrite only the employee sample mirrors whose content changed"
  },
  {
    "version": "v150.25",
    "date": "2026-09-29",
    "bucket": "fix",
    "scope": "distribution",
    "title": "persist derived cache, sidecar and mirrors on a background chain instead of the reassign click path"
  },
  {
    "version": "v150.24",
    "date": "2026-09-29",
    "bucket": "fix",
    "scope": "population",
    "title": "read the prior-month advisory only when Phase 3 is visible"
  },
  {
    "version": "v150.23",
    "date": "2026-09-29",
    "bucket": "fix",
    "scope": "referral",
    "title": "reload only the decided month after an approval decision"
  },
  {
    "version": "v150.22",
    "date": "2026-09-29",
    "bucket": "fix",
    "scope": "referral",
    "title": "fail fast when the share refuses to replace the requests file"
  }
];
