// AUTO-GENERATED by scripts/generate-changelog-data.mjs from docs/edit logs/ — do not hand-edit.
// Regenerate with `npm run generate:changelog` (also runs automatically before dev/build/test/typecheck).

import type { ChangelogEntry } from "./changelogTypes";

export const LATEST_UPDATES: ChangelogEntry[] = [
  {
    "version": "v133.0",
    "date": "2026-09-08",
    "bucket": "fix",
    "scope": "workspace-reads",
    "title": "a failed read is no longer presented as empty data"
  },
  {
    "version": "v132.1",
    "date": "2026-09-03",
    "bucket": "fix",
    "scope": "referral-approval",
    "title": "stop discarding the diagnostic when a decision write fails"
  },
  {
    "version": "v132.0",
    "date": "2026-09-03",
    "bucket": "feature",
    "scope": "history",
    "title": "rolling last-10 pre-change snapshot history for templates, answers, and distribution admin edits"
  },
  {
    "version": "v131.21",
    "date": "2026-09-03",
    "bucket": "fix",
    "scope": "templates",
    "title": "resolve each answer's own template in the live inspection panel, not just the results table"
  },
  {
    "version": "v131.20",
    "date": "2026-09-03",
    "bucket": "fix",
    "scope": "templates",
    "title": "keep answered-under-a-deleted-template results resolvable by question label"
  },
  {
    "version": "v131.19",
    "date": "2026-09-03",
    "bucket": "fix",
    "scope": "e2e",
    "title": "update employee-queue.spec.ts's case-chip counts for the مستهدف المؤشر redefinition"
  },
  {
    "version": "v131.18",
    "date": "2026-09-03",
    "bucket": "redesign",
    "scope": "employee-workspace",
    "title": "extract the queue's selection helpers so XrayReferrals clears the max-lines gate again"
  },
  {
    "version": "v131.17",
    "date": "2026-09-03",
    "bucket": "enhancement",
    "scope": "employee-workspace",
    "title": "مستهدف المؤشر now means 'from the regular population pipeline', not a risk-column read"
  },
  {
    "version": "v131.16",
    "date": "2026-09-03",
    "bucket": "fix",
    "scope": "employee-workspace",
    "title": "queue الحالة filter no longer misses مستبدلة rows or conflates معلق with مكتملة"
  },
  {
    "version": "v131.15",
    "date": "2026-09-03",
    "bucket": "fix",
    "scope": "executive-deck-v3",
    "title": "paginate port tables to stop overflow past the slide edge"
  }
];
