// AUTO-GENERATED by scripts/generate-changelog-data.mjs from docs/edit logs/ — do not hand-edit.
// Regenerate with `npm run generate:changelog` (also runs automatically before dev/build/test/typecheck).

import type { ChangelogEntry } from "./changelogTypes";

export const LATEST_UPDATES: ChangelogEntry[] = [
  {
    "version": "v153.0",
    "date": "2026-10-07",
    "bucket": "feature",
    "scope": "results",
    "title": "«المتابعة والمواعيد» default tab — admin-settable deadline, quota, calendar, per-employee averages"
  },
  {
    "version": "v152.0",
    "date": "2026-10-07",
    "bucket": "feature",
    "scope": "deck2",
    "title": "editable static text in the executive deck, saved as named presets"
  },
  {
    "version": "v151.8",
    "date": "2026-10-06",
    "bucket": "feature",
    "scope": "reports",
    "title": "per-page print on/off toggles, select all/none and saved selection in the executive HTML decks (v2, v3)"
  },
  {
    "version": "v151.7",
    "date": "2026-10-06",
    "bucket": "fix",
    "scope": "deck3",
    "title": "split the last two visual slides into two (يتبع) pages each"
  },
  {
    "version": "v151.6",
    "date": "2026-10-06",
    "bucket": "fix",
    "scope": "deck3",
    "title": "chart axes widen to fit real data so low/high values keep a visible bar and label"
  },
  {
    "version": "v151.5",
    "date": "2026-10-06",
    "bucket": "fix",
    "scope": "workbookImport",
    "title": "read the examined-sample layout (SJAN…SDEC) of the comprehensive report workbook"
  },
  {
    "version": "v151.4",
    "date": "2026-10-06",
    "bucket": "redesign",
    "scope": "reports",
    "title": "deck3 scope wording moved to deck3Copy() to stay under the complexity gate"
  },
  {
    "version": "v151.3",
    "date": "2026-10-06",
    "bucket": "fix",
    "scope": "tests",
    "title": "FeedbackWidget test sessions no longer expire with the calendar"
  },
  {
    "version": "v151.2",
    "date": "2026-10-06",
    "bucket": "fix",
    "scope": "reports",
    "title": "comprehensive report renumbers sections, drops the population rail tab, supports deck v3, and states its study period"
  },
  {
    "version": "v151.1",
    "date": "2026-10-06",
    "bucket": "fix",
    "scope": "reports",
    "title": "comprehensive report opens the executive deck, not the detailed document"
  }
];
