# One-time generator for public/app-icon.ico. Reproduces the shapes of the
# inline SVG favicon in index.html (navy rounded-square mark, white "film"
# panel, three scan lines, teal checkmark badge) at 16/32/48/256px using
# GDI+ primitives, then hand-assembles a real multi-resolution Windows ICO
# with PNG-compressed frames. Re-run only if the brand mark changes — the
# output is committed to git, not regenerated by any build step.

$ErrorActionPreference = "Stop"
Add-Type -AssemblyName System.Drawing

$outputPath = Join-Path $PSScriptRoot "..\public\app-icon.ico"
$sizes = @(16, 32, 48, 256)

function New-RoundedRectPath {
    param([float]$X, [float]$Y, [float]$W, [float]$H, [float]$R)
    $path = New-Object System.Drawing.Drawing2D.GraphicsPath
    $d = $R * 2
    $path.AddArc($X, $Y, $d, $d, 180, 90)
    $path.AddArc($X + $W - $d, $Y, $d, $d, 270, 90)
    $path.AddArc($X + $W - $d, $Y + $H - $d, $d, $d, 0, 90)
    $path.AddArc($X, $Y + $H - $d, $d, $d, 90, 90)
    $path.CloseFigure()
    return $path
}

function New-IconFrame {
    param([int]$Size)

    $bmp = New-Object System.Drawing.Bitmap($Size, $Size)
    $g = [System.Drawing.Graphics]::FromImage($bmp)
    $g.SmoothingMode = [System.Drawing.Drawing2D.SmoothingMode]::AntiAlias
    $g.Clear([System.Drawing.Color]::Transparent)

    $scale = $Size / 96.0
    $navy  = [System.Drawing.Color]::FromArgb(255, 0x17, 0x36, 0x5D)
    $film  = [System.Drawing.Color]::FromArgb(255, 0xF8, 0xFB, 0xFF)
    $teal  = [System.Drawing.Color]::FromArgb(255, 0x00, 0xA3, 0xA3)
    $white = [System.Drawing.Color]::White

    $bgPath = New-RoundedRectPath -X 0 -Y 0 -W $Size -H $Size -R (18 * $scale)
    $g.FillPath((New-Object System.Drawing.SolidBrush($navy)), $bgPath)

    $filmPath = New-RoundedRectPath -X (32 * $scale) -Y (30 * $scale) -W (32 * $scale) -H (28 * $scale) -R (8 * $scale)
    $g.FillPath((New-Object System.Drawing.SolidBrush($film)), $filmPath)

    if ($Size -ge 32) {
        $pen = New-Object System.Drawing.Pen($navy, [Math]::Max(1.5, 5 * $scale))
        $pen.StartCap = [System.Drawing.Drawing2D.LineCap]::Round
        $pen.EndCap = [System.Drawing.Drawing2D.LineCap]::Round
        $g.DrawLine($pen, (36 * $scale), (38 * $scale), (60 * $scale), (38 * $scale))
        $g.DrawLine($pen, (36 * $scale), (48 * $scale), (68 * $scale), (48 * $scale))
        $g.DrawLine($pen, (36 * $scale), (58 * $scale), (56 * $scale), (58 * $scale))
    }

    $badgeR = 10 * $scale
    $badgeCx = 66 * $scale
    $badgeCy = 60 * $scale
    $g.FillEllipse((New-Object System.Drawing.SolidBrush($teal)), ($badgeCx - $badgeR), ($badgeCy - $badgeR), ($badgeR * 2), ($badgeR * 2))

    if ($Size -ge 32) {
        $checkPen = New-Object System.Drawing.Pen($white, [Math]::Max(1, 3 * $scale))
        $checkPen.StartCap = [System.Drawing.Drawing2D.LineCap]::Round
        $checkPen.EndCap = [System.Drawing.Drawing2D.LineCap]::Round
        $checkPen.LineJoin = [System.Drawing.Drawing2D.LineJoin]::Round
        $pts = New-Object System.Drawing.PointF[] 3
        $pts[0] = New-Object System.Drawing.PointF((62 * $scale), (60 * $scale))
        $pts[1] = New-Object System.Drawing.PointF((65 * $scale), (63 * $scale))
        $pts[2] = New-Object System.Drawing.PointF((71 * $scale), (56 * $scale))
        $g.DrawLines($checkPen, $pts)
    }

    $g.Dispose()
    return $bmp
}

function ConvertTo-PngBytes {
    param([System.Drawing.Bitmap]$Bitmap)
    $ms = New-Object System.IO.MemoryStream
    $Bitmap.Save($ms, [System.Drawing.Imaging.ImageFormat]::Png)
    return $ms.ToArray()
}

$frames = foreach ($size in $sizes) {
    $bmp = New-IconFrame -Size $size
    $png = ConvertTo-PngBytes -Bitmap $bmp
    $bmp.Dispose()
    [pscustomobject]@{ Size = $size; Png = $png }
}

$stream = New-Object System.IO.MemoryStream
$writer = New-Object System.IO.BinaryWriter($stream)

$writer.Write([UInt16]0)
$writer.Write([UInt16]1)
$writer.Write([UInt16]$frames.Count)

$headerSize = 6 + (16 * $frames.Count)
$offset = $headerSize
foreach ($frame in $frames) {
    $dim = if ($frame.Size -ge 256) { 0 } else { [byte]$frame.Size }
    $writer.Write([byte]$dim)
    $writer.Write([byte]$dim)
    $writer.Write([byte]0)
    $writer.Write([byte]0)
    $writer.Write([UInt16]1)
    $writer.Write([UInt16]32)
    $writer.Write([UInt32]$frame.Png.Length)
    $writer.Write([UInt32]$offset)
    $offset += $frame.Png.Length
}
foreach ($frame in $frames) {
    $writer.Write($frame.Png, 0, $frame.Png.Length)
}

$writer.Flush()
[System.IO.File]::WriteAllBytes($outputPath, $stream.ToArray())
$writer.Dispose()
$stream.Dispose()

Write-Host "Wrote $outputPath ($($frames.Count) frames: $($sizes -join ', ')px)" -ForegroundColor Green
